export const selector = {
  buttonFountainCopy: document.getElementById('copy-fountain'),
  buttonFountainSave: document.getElementById('save-fountain'),
  buttonFountainShare: document.getElementById('share-fountain'),
  buttonMobileSwitch: document.getElementById('mobile-switch'),
  buttonPrint: document.getElementById('print'),
  buttonTxtCopy: document.getElementById('copy-txt'),
  buttonTxtOpen: document.getElementById('open-txt'),
  buttonTxtSave: document.getElementById('save-txt'),
  buttonTxtShare: document.getElementById('share-txt'),
  fileOpenTXT: document.getElementById('open_txt_file'),
  input: document.getElementById('input'),
  paneLeft: document.querySelector('.left-pane'),
  paneRight: document.querySelector('.right-pane'),
  result: document.getElementById('result'),
  resultShadowBottom: document.querySelector('.result-container .overflow-shadow.bottom'),
  resultShadowTop: document.querySelector('.result-container .overflow-shadow.top'),
  zoom: document.getElementById('zoom'),
  zoomContainer: document.getElementById('zoom-container'),
  zoomNumber: document.getElementById('zoom-number'),
};